<html>
<head>
<title>contohPenggunaanIF</title>
</head>
<body>
<h3>Menentukanbilanganganjil/genap</h3>
<formmethod="post"action="">
MasukanNilai:
<inputtype=textname=input1><br><br>
<inputtype=submitvalue="Proses">
</form>
<?php
if(isset($_POST['input1']))
{
$nilai=intval($_POST['input1']);
if($nilai%2==0)
printf("$nilaimerupakanbilanggenap");
else
printf("$nilaimerupakanbilangganjil");;
}
?>
</body>
</html>
