<html>
<head>
<title>PenggunaanSwitch- Case</title>
</head>
<body>
    <?Php
$namahari=date("l");
Switch($namahari)
{
Case"Sunday";
Print("Minggu");
print"Waktuuntukistirahat";
Break;
Case"Monday";
Print("Senin<br>");
print"Meetingawalminggujam08.00";
Break;
Case"Tuesday";
Print("Selasa<br>");
print"PembukaanWorkshopDiklat";
Break;
Case"Wednesday";
Print("Rabu<br>");
print("SeminarLaunchigWindowVistadiJHCC");
Break;
Case"Thrusday";
Print("Kamis<br>");
print"PertemuandenganMahasiswa";
Break;
Case"Friday";
Print("Jum’at<br>");
print"Joggingbersama";
Break;
Default:
Print("Sabtu<br>");
print"SurveyhargakeDusit,ManggaDua";
}
?>
</body>
</html>
ContohpenggunaanSwicth– Case:
<?php
echo"<u>MenuPilihan</u><br>";
echo"[1]Trapesium<br>";
echo"[2]PersegiPanjang<br>";
echo"[3]BujusSangkar<br><br>";
echo"<formmethod='post'>";
echo"Pilihan<inputtype='text'name='pilih'size=2>";
echo"<inputtype='submit'value='kirim'><br>";
$pil=$_POST['pilih'];
switch($pil)
{
case1:
$atas=12;$bawah=17;$tinggi=7;
$luas=($atas+$bawah)/2*$tinggi;
echo"<br>MencariLuasTrapesium<br>";
echo"Garisatas=$atascm<br>";
echo"Garisbawah=$bawahcm<br>";
echo"Tinggi=$tinggicm<br>";
echo"LuasTrapesium=$luascm<sup>2</sup><br>";
break;
case2:
$panjang1=25;$lebar1=14;
$luas1=$panjang1*$lebar1;
echo"<br>MencariLuasPersegiPanjang<br>";
echo"Panjang=$panjang1 cm<br>";
echo"Lebar=$lebar1 cm<br>";
echo"LuasBujurSangkar=$luas1 cm<sup>2</sup><br>";
break;
case3:
$sisi=12;
$luas=$sisi*$sisi;
echo"<br>MencariLuasBujurSangkar<br>";
echo"Sisi=$sisicm<br>";
echo"LuasBujurSangkar=$luascm<sup>2</sup><br>";
break;
default:
echo"<br><blink>Pilihanandasalah,silakancobalagi</blink>";
break;
}
?>
