<?php
$tujuan="Tokyo";
Switch($tujuan){
case"LasVegas":
echo"Bringanextra$500";
break;
case"Amsterdam":
echo"Bringanopenmind";
break;
case"Egypt":
echo"Bring15bottlesofSPF50Sunscreen";
break;
case"Tokyo":
echo"Bringlotsofmoney";
break;
case"CaribbeanIslands":
echo"Bringaswimsuit";
break;
}
?>