<html>
<head>
<title>ImplementasiIF ..ELSEIF</title>
</head>
<body>
<formmethod="post"action="">
MasukanNilai:
<inputtype=textname=input1><br><br>
<inputtype=submitvalue="Proses">
</form>
<?php
if(isset($_POST['input1']))
{
$nilai=intval($_POST['input1']);
if($nilai>=80)
printf("andalulusdenganmendapatkangradeA");
elseif($nilai>=70)
printf("andalulusdenganmendapatkangradeB");
elseif($nilai>=60)
printf("andalulusdenganmendapatkangradeC");
elseif($nilai>=50)
printf("andatidaklulus,gradeD");
else
printf("andatidaklulus,gradeE");;
}
?>
</body>
</html>